### ISSUE TITLE
Socket hang up error upon stream reconnect

### ISSUE THREAD

**Issue by MeanwhileMedia** [ttezel/twit#117]
I close, then reopen a streaming api connection about every 10 minutes. The reconnects were working fine until I updated to node v0.10.28. Now I get socket hang ups when I try to reconnect, which result in a fatal error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: socket hang up
    at SecurePair.error (tls.js:1013:23)
    at EncryptedStream.CryptoStream._done (tls.js:705:22)
    at CleartextStream.read [as _read] (tls.js:496:24)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.onCryptoStreamFinish (tls.js:301:47)
    at EncryptedStream.g (events.js:180:16)
    at EncryptedStream.EventEmitter.emit (events.js:117:20)
    at finishMaybe (_stream_writable.js:360:12)
    at endWritable (_stream_writable.js:367:3)
    at EncryptedStream.Writable.end (_stream_writable.js:345:5)
```

The initial connection is working fine. It is the disconnect/reconnect that breaks things.

I'm also noticing that node-oauth (through twit) is attempting to open new connections at seemingly random times with no explanation or reason. Some things definitely seem to be off with twit and the newest version of node. 

@ttezel, everything still working alright on your end? Have you had the chance to do any testing on the newest version of Node? Do you think this is an issue with node-oauth? I opened an issue in the node-oauth repo as well which has additional details: https://github.com/ciaranj/node-oauth/issues/199

I'm using twit 1.1.15 (current version)

thanks

**Comment by ttezel** [comment]
Closing this - some of the reconnect logic has been fixed. If you still see this with twit v`1.1.20` please reopen!

**Comment by MeanwhileMedia** [comment]
Sounds good thanks @ttezel
