### ISSUE TITLE
Continuously getting 401 error on Stream

### ISSUE THREAD

**Issue by markov00** [ttezel/twit#158]
Hi, I'm try to use the library to get a stream of data but I'm getting a 401 error. I've checked the API tokens and they are fine. I've also try to use the library with a simple T.get and I receive correctly the data with the token used.

This is the error I'm getting:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Bad Twitter streaming request: 401
    at ClientRequest.<anonymous> (/home/data/app/node_modules/twit/lib/oarequest.js:201:19)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
    at CleartextStream.read [as _read] (tls.js:511:12)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:226:10)

**Comment by yellowiscool** [comment]
Hi. I have exactly the same problem.

**Comment by gabrielstuff** [comment]
You should put the request you make / the code you write.
I never got this issue.

**Comment by kyr0** [comment]
// app.js
var Twit = require('twit');

var T = new Twit({
    consumer_key: '$myVerifiedCorrectConsumerKey',
    consumer_secret: ''$myVerifiedCorrectConsumerSecret',
    app_only_auth: true
});

var stream = T.stream('statuses/filter', {track: ['FOREX', 'EUR rate', 'USD rate', 'EUR', 'USD']});

stream.on('tweet', function(tweet) {

    console.log(tweet);
});


---

> node app.js

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Bad Twitter streaming request: 401
    at Object.exports.makeTwitError (/Users/aronhomberg/Source/ONPEX-Idea/Twitalyzer/node_modules/twit/lib/helpers.js:74:13)
    at IncomingMessage.<anonymous> (/Users/aronhomberg/Source/ONPEX-Idea/Twitalyzer/node_modules/twit/lib/streaming-api-connection.js:92:29)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)

**Comment by sohailriaz** [comment]
Error: Bad Twitter streaming request: 401
at ClientRequest. (E:\Nexthon\newstemplate\ngTwitterApp-master\ngTwitterAp
p-master\node_modules\twit\lib\oarequest.js:202:19)
at ClientRequest.g (events.js:291:16)
at emitOne (events.js:96:13)
at ClientRequest.emit (events.js:188:7)
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
at TLSSocket.socketOnData (_http_client.js:362:20)
at emitOne (events.js:96:13)
at TLSSocket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
I have this error any one help me
