### ISSUE TITLE
Script exits on 406

### ISSUE THREAD

**Issue by piotryordanov** [ttezel/twit#177]
I am getting the following error:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Bad Twitter streaming request: 406
  at ClientRequest.<anonymous> (/root/apps/docker-watson/source/node_modules/twit/lib/oarequest.js:202:19)
  at ClientRequest.g (events.js:199:16)
  at ClientRequest.emit (events.js:107:17)
  at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:419:21)
  at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
  at TLSSocket.socketOnData (_http_client.js:310:20)
  at TLSSocket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at TLSSocket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:529:20)
```

And the my script dies.
I personally am fine with having the stream fail, as long as i can restart the stream without having to restart the actual process. Is this possible?

**Comment by ttezel** [comment]
Hi @piotryordanov this shouldn't be happening anymore since that is very old code. Run `npm update twit` to get the latest version! Thanks :)

**Comment by piotryordanov** [comment]
@ttezel awesome thx :)
