### ISSUE TITLE
Unable to upload MP4 media

### ISSUE THREAD

**Issue by JNalv** [ttezel/twit#183]
So the REST API now [supports the upload of video](https://blog.twitter.com/2015/rest-api-now-supports-native-video-upload). Cool stuff! [Guidelines here.](https://dev.twitter.com/rest/public/uploading-media)

I've managed to get an authenticate-able POST request together, but I get the following error:

```
{ [Error: Unknown Twitter API Error]
  message: 'Unknown Twitter API Error',
  statusCode: 400,
  twitterReply: '{"request":"\\/1.1\\/media\\/upload.json","error":"media type unrecognized."}',
  code: null,
  allErrors: [] }
```

I triple-checked that the .mp4 itself is fine, in size, dimension, FPS, and audio (side note: the docs don't say it yet, but they only support mono & stereo — no 5.1 sound).

From what I can tell, it looks like the 'Content-Type' in the POST request might not be set correctly. Unfortunately, this is the limit of my understanding. Is this an issue with the lib, or something that I'm doing wrong?

**Comment by bcomnes** [comment]
As far as I can tell this library does not support video uploads.  I've been trying to figure this out using request, but twitter decided to make a totally difficult endpoint to use.

**Comment by gabrielstuff** [comment]
Hi @bcomnes and @JNalv, I just fixed the issues that would not allow Twit to post video media file type.
It is based on some wrong assumption about the form data which is stringified and parsed to be cloned and the fact that the body response should always contain a JSON.
This is not the case when using video. As the twitter doc says the video media upload should use the CHUNK api : https://dev.twitter.com/rest/public/uploading-media#chunkedupload.

I just made an example using this Chunk api and upadte the twit code part.

I'll made a few test and pull request.

Thanks

**Comment by bcomnes** [comment]
I ended up writing https://github.com/bcomnes/twitter-video as well.

**Comment by ttezel** [comment]
Hi @JNalv @bcomnes @gabrielstuff this has been added to twit! `npm update twit` to get it and check out the readme for examples! For the lazy:
```js
//
// post a tweet with media
//
var b64content = fs.readFileSync('/path/to/img', { encoding: 'base64' })

// first we must post the media to Twitter
T.post('media/upload', { media_data: b64content }, function (err, data, response) {

  // now we can reference the media and post a tweet (media will attach to the tweet)
  var mediaIdStr = data.media_id_string
  var params = { status: 'loving life #nofilter', media_ids: [mediaIdStr] }

  T.post('statuses/update', params, function (err, data, response) {
    console.log(data)
  })
})

//
// post media via the chunked media upload API.
// You can then use POST statuses/update to post a tweet with the media attached as in the example above using `media_id_string`.
// Note: You can also do this yourself manually using T.post() calls if you want more fine-grained
// control over the streaming. Example: https://github.com/ttezel/twit/blob/master/tests/rest_chunked_upload.js#L20
//
var filePath = '/absolute/path/to/file.mp4'
T.postMediaChunked({ file_path: filePath }, function (err, data, response) {
  console.log(data)
})
```

**Comment by hoodsy** [comment]
@ttezel I'm trying to upload larger videos, and got the error: 

```
Error: This file is too large. Max size is 15728640B. Got: 135144453B.
      at [object Object].FileUploader._initMedia (/home/logan/impressiv/node_modules/twit/lib/file_uploader.js:139:8)
      at [object Object].FileUploader.upload (/home/logan/impressiv/node_modules/twit/lib/file_uploader.js:39:8)
      at [object Object].Twitter.postMediaChunked (/home/logan/impressiv/node_modules/twit/lib/twitter.js:152:16)
      at tweet.js:109:21
      at new Promise (/home/logan/impressiv/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:191:7)
      at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/home/logan/impressiv/node_modules/core-js/library/modules/$.export.js:30:36)
      at _callee6$ (tweet.js:108:18)
      at tryCatch (/home/logan/impressiv/node_modules/babel-runtime/regenerator/runtime.js:72:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/home/logan/impressiv/node_modules/babel-runtime/regenerator/runtime.js:334:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/logan/impressiv/node_modules/babel-runtime/regenerator/runtime.js:105:21)
      at step (/home/logan/impressiv/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /home/logan/impressiv/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at new Promise (/home/logan/impressiv/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:191:7)
      at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/home/logan/impressiv/node_modules/core-js/library/modules/$.export.js:30:36)
      at /home/logan/impressiv/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
      at createMedia (/home/logan/impressiv/server/routes/tweet.js:316:18)
      at _callee5$ (tweet.js:81:21)
      at tryCatch (/home/logan/impressiv/node_modules/babel-runtime/regenerator/runtime.js:72:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/home/logan/impressiv/node_modules/babel-runtime/regenerator/runtime.js:334:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/logan/impressiv/node_modules/babel-runtime/regenerator/runtime.js:105:21)
      at step (/home/logan/impressiv/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /home/logan/impressiv/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
```

How can I specify the maxSize for uploads?
