### ISSUE TITLE
Problem with track filter, exits with 406

### ISSUE THREAD

**Issue by anamritraj** [ttezel/twit#184]
Sorry if I'm noob. I'm new to Github.
When I run the following code:
```
var words = ['mango','cats','chocolate'];
var stream = T.stream('statuses/sample', { track: words });

stream.on('tweet', function (tweet) {
  console.log(tweet.text);
});
```

The above code throws following error:
```
C:\Users\anamritraj\Desktop\twitter-growthhack-toolkit-master>node index.js
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Bad Twitter streaming request: 406
    at ClientRequest.<anonymous> (C:\Users\anamritraj\Desktop\twitter-growthhack-toolkit-master\node_module
s\twit\lib\oarequest.js:202:19)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:426:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at TLSSocket.socketOnData (_http_client.js:317:20)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at TLSSocket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

however this code works fine:
```
var sanFrancisco = [ '-122.75', '36.8', '-121.75', '37.8' ];
var stream = T.stream('statuses/sample', { location: sanFrancisco });

stream.on('tweet', function (tweet) {
  console.log(tweet.text);
});
```

**Comment by ivaylopg** [comment]
var words = ['mango','cats','chocolate'];

should be:

var words = 'mango,cats,chocolate';

the **track** parameter is looking for a string, not an array object.
