### ISSUE TITLE
Deploy to Heroku?

### ISSUE THREAD

**Issue by neeravmakwana** [ttezel/twit#187]
I have created a bot which is running perfectly locally (windows PC). The purpose is to search for something, randomise the search result and retweet and follow that person. Repeat the process every x minutes.

I'm trying to upload it to Heroku as currently it runs only when my PC is switched on. I tried following a lot of guides online including the ones on Heroku website, but I;m unable to deploy. Any suggestions?

**Comment by ttezel** [comment]
What kind of issues are you having?

**Comment by neeravmakwana** [comment]
I'm following everything as mentioned in Heroku guide. But, opening the application page https://sleepy-harbor-7515.herokuapp.com is giving the error:
"An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details."

The logs have multiple errors including: Cannot find module twit, module.require (module.js). The log is as below:

C:/Users/makwana/.heroku/client/vendor/gems/excon-0.45.2/lib/excon/connection.rb
:389:in `socket'
C:/Users/makwana/.heroku/client/vendor/gems/excon-0.45.2/lib/excon/connection.rb
:106:in `request_call'
C:/Users/makwana/.heroku/client/vendor/gems/excon-0.45.2/lib/excon/middlewares/m
ock.rb:47:in `request_call'
C:/Users/makwana/.heroku/client/vendor/gems/excon-0.45.2/lib/excon/middlewares/i
nstrumentor.rb:22:in `request_call'
C:/Users/makwana/.heroku/client/vendor/gems/excon-0.45.2/lib/excon/middlewares/b
ase.rb:15:in `request_call'
C:/Users/makwana/.heroku/client/vendor/gems/excon-0.45.2/lib/excon/middlewares/b
ase.rb:15:in `request_call'
C:/Users/makwana/.heroku/client/vendor/gems/excon-0.45.2/lib/excon/middlewares/b
ase.rb:15:in `request_call'
C:/Users/makwana/.heroku/client/vendor/gems/excon-0.45.2/lib/excon/connection.rb
:233:in `request'
C:/Users/makwana/.heroku/client/vendor/gems/excon-0.45.2/lib/excon.rb:229:in `ge
t'
C:/Users/makwana/.heroku/client/lib/heroku/excon.rb:4:in `get_with_redirect'
C:/Users/makwana/.heroku/client/lib/heroku/updater.rb:36:in `http_get'
C:/Users/makwana/.heroku/client/lib/heroku/updater.rb:26:in `latest_version'
C:/Users/makwana/.heroku/client/lib/heroku/updater.rb:50:in `needs_update?'
C:/Users/makwana/.heroku/client/lib/heroku/updater.rb:109:in `update'
C:/Users/makwana/.heroku/client/lib/heroku/updater.rb:101:in `autoupdate'
C:/Users/makwana/.heroku/client/lib/heroku/cli.rb:28:in `start'
C:/Program Files/Heroku/bin/heroku:29:in `<main>'
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       getaddrinfo: This is usually a temporary error during hostname
resolution and means that the local server did not receive a response from an au
thoritative server.  (SocketError) (Excon::Errors::SocketError)
    Command:     heroku login
    Version:     heroku/toolbelt/3.39.0 (i386-mingw32) ruby/1.9.3


    More information in C:/Users/makwana/.heroku/error.log


C:\node_modules\twit\examples>git push heroku master
Counting objects: 5, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 383 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  >=0.6.0
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version >=0.6.0 via semver.io...
remote:        Downloading and installing node 0.12.6...
remote:        Using default npm version: 2.11.2
remote:
remote: -----> Restoring cache
remote:        Loading 1 from cacheDirectories (default):
remote:        - node_modules
remote:
remote: -----> Building dependencies
remote:        Pruning any extraneous modules
remote:        Installing node modules (package.json)
remote:
remote: -----> Caching build
remote:        Clearing previous node cache
remote:        Saving 1 cacheDirectories (default):
remote:        - node_modules
remote:
remote: -----> Build succeeded!
remote:        └── oauth@0.9.9
remote:
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:
remote: -----> Compressing... done, 9.4MB
remote: -----> Launching... done, v7
remote:        https://sleepy-harbor-7515.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.

Warning: Your console font probably doesn't support Unicode. If you experience s
trange characters in the output, consider switching to a TrueType font such as L
ucida Console!
To https://git.heroku.com/sleepy-harbor-7515.git
   6fef4ac..feb80bb  master -> master

C:\node_modules\twit\examples>heroku ps:scale web=1
Scaling dynos... failed
 !    Unable to connect to Heroku API, please check internet connectivity and tr
y again.

C:\node_modules\twit\examples>heroku ps:scale web=1
Scaling dynos... failed
 !    Unable to connect to Heroku API, please check internet connectivity and tr
y again.

C:\node_modules\twit\examples>heroku ps:scale web=1
Scaling dynos... failed
 !    Unable to connect to Heroku API, please check internet connectivity and tr
y again.

C:\node_modules\twit\examples>heroku ps:scale web=1
Scaling dynos... done, now running web at 1:Free.

C:\node_modules\twit\examples>heroku open
Opening sleepy-harbor-7515... done

C:\node_modules\twit\examples>heroku logs --tail
2015-07-05T22:01:20.373235+00:00 app[web.1]:     at Module.require (module.js:36
5:17)
2015-07-05T22:01:20.373234+00:00 app[web.1]:     at Function.Module._load (modul
e.js:278:25)
2015-07-05T22:01:20.373236+00:00 app[web.1]:     at require (module.js:384:17)
2015-07-05T22:01:20.373239+00:00 app[web.1]:     at Module._compile (module.js:4
60:26)
2015-07-05T22:01:20.373237+00:00 app[web.1]:     at Object.<anonymous> (/app/rt1
8.js:1:74)
2015-07-05T22:01:20.373240+00:00 app[web.1]:     at Object.Module._extensions..j
s (module.js:478:10)
2015-07-05T22:01:20.373241+00:00 app[web.1]:     at Module.load (module.js:355:3
2)
2015-07-05T22:01:20.373242+00:00 app[web.1]:     at Function.Module._load (modul
e.js:310:12)
2015-07-05T22:01:20.373244+00:00 app[web.1]:     at Function.Module.runMain (mod
ule.js:501:10)
2015-07-05T22:01:21.206184+00:00 heroku[web.1]: State changed from starting to c
rashed
2015-07-05T22:01:21.190470+00:00 heroku[web.1]: Process exited with status 1
2015-07-06T21:07:07.645419+00:00 heroku[web.1]: State changed from crashed to st
arting
2015-07-06T21:07:10.328415+00:00 heroku[web.1]: Starting process with command `n
ode rt18.js`
2015-07-06T21:07:12.700592+00:00 app[web.1]: Detected 512 MB available memory, 5
12 MB limit per process (WEB_MEMORY)
2015-07-06T21:07:12.700612+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-07-06T21:07:13.077186+00:00 app[web.1]: module.js:338
2015-07-06T21:07:13.077195+00:00 app[web.1]:           ^
2015-07-06T21:07:13.077193+00:00 app[web.1]:     throw err;
2015-07-06T21:07:13.077197+00:00 app[web.1]: Error: Cannot find module 'twit'
2015-07-06T21:07:13.077198+00:00 app[web.1]:     at Function.Module._resolveFile
name (module.js:336:15)
2015-07-06T21:07:13.077201+00:00 app[web.1]:     at Module.require (module.js:36
5:17)
2015-07-06T21:07:13.077203+00:00 app[web.1]:     at require (module.js:384:17)
2015-07-06T21:07:13.077200+00:00 app[web.1]:     at Function.Module._load (modul
e.js:278:25)
2015-07-06T21:07:13.077208+00:00 app[web.1]:     at Module.load (module.js:355:3
2)
2015-07-06T21:07:13.077213+00:00 app[web.1]:     at Function.Module.runMain (mod
ule.js:501:10)
2015-07-06T21:07:13.077204+00:00 app[web.1]:     at Object.<anonymous> (/app/rt1
8.js:1:74)
2015-07-06T21:07:13.077206+00:00 app[web.1]:     at Module._compile (module.js:4
60:26)
2015-07-06T21:07:13.077207+00:00 app[web.1]:     at Object.Module._extensions..j
s (module.js:478:10)
2015-07-06T21:07:13.077212+00:00 app[web.1]:     at Function.Module._load (modul
e.js:310:12)
2015-07-06T21:07:14.116766+00:00 heroku[web.1]: State changed from starting to c
rashed
2015-07-06T21:07:14.099236+00:00 heroku[web.1]: Process exited with status 1
2015-07-07T16:32:23.514453+00:00 heroku[api]: Scale to web=1 by neeravmakwana@gm
ail.com
2015-07-07T16:33:03.880370+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/" host=sleepy-harbor-7515.herokuapp.com request_id=6df5b
423-c3ec-4079-8fe4-09ae279dd185 fwd="59.182.146.144" dyno= connect= service= sta
tus=503 bytes=
2015-07-07T16:33:06.458449+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/favicon.ico" host=sleepy-harbor-7515.herokuapp.com reque
st_id=781cc927-6339-4cf1-9322-df80f4d50c8d fwd="59.182.146.144" dyno= connect= s
ervice= status=503 bytes=
2015-07-07T20:00:30.298338+00:00 heroku[web.1]: State changed from crashed to st
arting
2015-07-07T20:00:33.071331+00:00 heroku[web.1]: Starting process with command `n
ode rt18.js`
2015-07-07T20:00:35.093141+00:00 app[web.1]: Detected 512 MB available memory, 5
12 MB limit per process (WEB_MEMORY)
2015-07-07T20:00:35.093170+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-07-07T20:00:35.492811+00:00 app[web.1]: Error: Cannot find module 'twit'
2015-07-07T20:00:35.492801+00:00 app[web.1]: module.js:338
2015-07-07T20:00:35.492807+00:00 app[web.1]:     throw err;
2015-07-07T20:00:35.492813+00:00 app[web.1]:     at Function.Module._resolveFile
name (module.js:336:15)
2015-07-07T20:00:35.492809+00:00 app[web.1]:           ^
2015-07-07T20:00:35.492814+00:00 app[web.1]:     at Function.Module._load (modul
e.js:278:25)
2015-07-07T20:00:35.492818+00:00 app[web.1]:     at require (module.js:384:17)
2015-07-07T20:00:35.492816+00:00 app[web.1]:     at Module.require (module.js:36
5:17)
2015-07-07T20:00:35.492819+00:00 app[web.1]:     at Object.<anonymous> (/app/rt1
8.js:1:74)
2015-07-07T20:00:35.492820+00:00 app[web.1]:     at Module._compile (module.js:4
60:26)
2015-07-07T20:00:35.492822+00:00 app[web.1]:     at Object.Module._extensions..j
s (module.js:478:10)
2015-07-07T20:00:35.492823+00:00 app[web.1]:     at Module.load (module.js:355:3
2)
2015-07-07T20:00:35.492825+00:00 app[web.1]:     at Function.Module._load (modul
e.js:310:12)
2015-07-07T20:00:35.492826+00:00 app[web.1]:     at Function.Module.runMain (mod
ule.js:501:10)
2015-07-07T20:00:36.394818+00:00 heroku[web.1]: State changed from starting to c
rashed
2015-07-07T20:00:36.377695+00:00 heroku[web.1]: Process exited with status 1
2015-07-08T16:23:11.501795+00:00 heroku[slug-compiler]: Slug compilation started

2015-07-08T16:23:11.501813+00:00 heroku[slug-compiler]: Slug compilation finishe
d
2015-07-08T16:23:11.452044+00:00 heroku[api]: Deploy feb80bb by neeravmakwana@gm
ail.com
2015-07-08T16:23:11.452044+00:00 heroku[api]: Release v7 created by neeravmakwan
a@gmail.com
2015-07-08T16:23:11.766361+00:00 heroku[web.1]: State changed from crashed to st
arting
2015-07-08T16:23:13.606876+00:00 heroku[web.1]: Starting process with command `n
ode rt18.js`
2015-07-08T16:23:15.512601+00:00 app[web.1]: Detected 512 MB available memory, 5
12 MB limit per process (WEB_MEMORY)
2015-07-08T16:23:15.512625+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-07-08T16:23:15.647641+00:00 app[web.1]: module.js:338
2015-07-08T16:23:15.647648+00:00 app[web.1]:           ^
2015-07-08T16:23:15.647647+00:00 app[web.1]:     throw err;
2015-07-08T16:23:15.647650+00:00 app[web.1]: Error: Cannot find module 'twit'
2015-07-08T16:23:15.647652+00:00 app[web.1]:     at Function.Module._resolveFile
name (module.js:336:15)
2015-07-08T16:23:15.647653+00:00 app[web.1]:     at Function.Module._load (modul
e.js:278:25)
2015-07-08T16:23:15.647655+00:00 app[web.1]:     at require (module.js:384:17)
2015-07-08T16:23:15.647656+00:00 app[web.1]:     at Object.<anonymous> (/app/rt1
8.js:1:74)
2015-07-08T16:23:15.647654+00:00 app[web.1]:     at Module.require (module.js:36
5:17)
2015-07-08T16:23:15.647657+00:00 app[web.1]:     at Module._compile (module.js:4
60:26)
2015-07-08T16:23:15.647658+00:00 app[web.1]:     at Object.Module._extensions..j
s (module.js:478:10)
2015-07-08T16:23:15.647660+00:00 app[web.1]:     at Module.load (module.js:355:3
2)
2015-07-08T16:23:15.647661+00:00 app[web.1]:     at Function.Module._load (modul
e.js:310:12)
2015-07-08T16:23:15.647662+00:00 app[web.1]:     at Function.Module.runMain (mod
ule.js:501:10)
2015-07-08T16:23:16.483281+00:00 heroku[web.1]: State changed from starting to c
rashed
2015-07-08T16:23:16.484508+00:00 heroku[web.1]: State changed from crashed to st
arting
2015-07-08T16:23:16.469683+00:00 heroku[web.1]: Process exited with status 1
2015-07-08T16:23:18.412602+00:00 heroku[web.1]: Starting process with command `n
ode rt18.js`
2015-07-08T16:23:20.164055+00:00 app[web.1]: Detected 512 MB available memory, 5
12 MB limit per process (WEB_MEMORY)
2015-07-08T16:23:20.164075+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-07-08T16:23:20.321576+00:00 app[web.1]: module.js:338
2015-07-08T16:23:20.321583+00:00 app[web.1]:     throw err;
2015-07-08T16:23:20.321585+00:00 app[web.1]:           ^
2015-07-08T16:23:20.321587+00:00 app[web.1]: Error: Cannot find module 'twit'
2015-07-08T16:23:20.321589+00:00 app[web.1]:     at Function.Module._resolveFile
name (module.js:336:15)
2015-07-08T16:23:20.321590+00:00 app[web.1]:     at Function.Module._load (modul
e.js:278:25)
2015-07-08T16:23:20.321592+00:00 app[web.1]:     at Module.require (module.js:36
5:17)
2015-07-08T16:23:20.321593+00:00 app[web.1]:     at require (module.js:384:17)
2015-07-08T16:23:20.321595+00:00 app[web.1]:     at Object.<anonymous> (/app/rt1
8.js:1:74)
2015-07-08T16:23:20.321596+00:00 app[web.1]:     at Module._compile (module.js:4
60:26)
2015-07-08T16:23:20.321597+00:00 app[web.1]:     at Object.Module._extensions..j
s (module.js:478:10)
2015-07-08T16:23:20.321599+00:00 app[web.1]:     at Module.load (module.js:355:3
2)
2015-07-08T16:23:20.321600+00:00 app[web.1]:     at Function.Module._load (modul
e.js:310:12)
2015-07-08T16:23:20.321601+00:00 app[web.1]:     at Function.Module.runMain (mod
ule.js:501:10)
2015-07-08T16:23:21.381028+00:00 heroku[web.1]: State changed from starting to c
rashed
2015-07-08T16:23:21.368665+00:00 heroku[web.1]: Process exited with status 1
2015-07-08T16:24:30.504311+00:00 heroku[api]: Scale to web=1 by neeravmakwana@gm
ail.com
2015-07-08T16:24:42.902529+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/" host=sleepy-harbor-7515.herokuapp.com request_id=ef2b8
5bc-16ef-45fc-a307-7242fc2c62fb fwd="59.182.162.228" dyno= connect= service= sta
tus=503 bytes=
2015-07-08T16:24:45.615108+00:00 heroku[router]: at=error code=H10 desc="App cra
shed" method=GET path="/favicon.ico" host=sleepy-harbor-7515.herokuapp.com reque
st_id=add9dad0-1d7b-48fb-9561-0cd3c3921807 fwd="59.182.162.228" dyno= connect= s
ervice= status=503 bytes=

**Comment by garbados** [comment]
are your bot's dependencies listed in your `package.json`?

**Comment by neeravmakwana** [comment]
Yes, there's just 1 dependency - the twit module and it's listed in package.json

In fact, when I tried deploying it again today, I'm getting the following error:

C:\test>git push heroku master
Counting objects: 655, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (592/592), done.
Writing objects: 100% (652/652), 900.95 KiB | 0 bytes/s, done.
Total 652 (delta 102), reused 0 (delta 0)
error: RPC failed; result=22, HTTP code = 504
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

I'm doing this on my Windows PC. As I said previously, it's working flawlessly on my local machine, but I don't want to keep it on 24x7 and hence I'm trying to deploy it on Heroku.

**Comment by noahmanion** [comment]
I think i can help with the first problem you're having:
*opening the application page https://sleepy-harbor-7515.herokuapp.com is giving the error:
"An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details."*

If you're running the bot included with the twit package, the reason you're being served the error page is that there isn't any front end architecture. the bot just runs a bunch of javascript files that print statuses to the console. there isn't anything for heroku to serve to the browser. you _can_ host the bot on heroku, but it needs to run at least once every 60 seconds and there won't be anything at your application's homepage. everything your bot does will be saved in the log files.
hopefully someone with more experience can correct any errors i have made.

**Comment by ttezel** [comment]
Closing this since it's heroku-specific.
