### ISSUE TITLE
stream list/statuses 401 error (works with get)

### ISSUE THREAD

**Issue by talyellin** [ttezel/twit#216]
```
var express = require('express');
var app = express();
var path = require('path');
var http = require('http').Server(app);
var Twit = require('twit');
var io = require('socket.io')(http);

var T = new Twit({
    consumer_key:         'xyz'
  , consumer_secret:      'xyz'
  , access_token:         'xyz'
  , access_token_secret:  'xyz'
  , app_only_auth:        true // should this be here?
})

io.on('connection', function (socket) {
    console.log('User connected. Socket id %s', socket.id);

    var stream = T.stream('lists/statuses', { owner_screen_name:'myHandle', owner_id: 'myID', include_rts:'true', slug: 'listName' })

    stream.on('tweet', function (tweet) {
        console.log(tweet)
    });

});
```
yields this error:

```
listening on: 3000
User connected. Socket id MUi6beVkQgHC4Y2FAAAA
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Bad Twitter streaming request: 401
    at Object.exports.makeTwitError (../node_modules/twit/lib/helpers.js:74:13)
    at IncomingMessage.<anonymous> (../node_modules/twit/lib/streaming-api-connection.js:92:29)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```
thanks

**Comment by talyellin** [comment]
It looks like lists are not supported with the Streaming API. I solved this by creating a new twitter account and just following the same people from my custom list. 
```
// I then used the following to import statuses
var stream = T.stream('user', { id: 'user_name' })
```
I was still getting an error, turns out my computer clock was ahead, which I fixed by enabling 'Set date and time automatically' in my osx Date & Time preferences.
