### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ORESoftware** [ttezel/twit#227]
I have this code in a Node.js Express server

```
var twitClient = new Twit({
    consumer_key: TWITTER_ORESOFTWARE_CONFIG.consumer_key,
    consumer_secret: TWITTER_ORESOFTWARE_CONFIG.consumer_secret,
    access_token: TWITTER_ORESOFTWARE_CONFIG.access_token,
    access_token_secret: TWITTER_ORESOFTWARE_CONFIG.access_token_secret
});
```

```js
router.get('/followers_list_cursor', Checks.isLoggedIn, function (req, res, next) {

    //note: https://dev.twitter.com/rest/reference/get/followers/list

    var user = req.user || req.proxyUser;
    var data = req.query.data ? JSON.parse(req.query.data) : {};
    var cursorNum = data.cursorNum;


    var params = {
        user_id: user.userId,
        count: 30,
        cursor: cursorNum === 0 ? 0 : cursorNum || -1  //default to -1, but allow for falsy 0
    };


    twitClient.get('followers/list', params, function (err, resp) {
        if (err) {
            console.error(err);
            next(err);
        }
        else if (resp.users) {

            res.json({
                success: resp.users
            });

        }
        else {
            next(new Error('no response'));
        }

    });

});
```

I keep getting this error, but non-deterministically - 

```
 Error: Sorry, that page does not exist.
    at Object.exports.makeTwitError (/Users/amills001c/WebstormProjects/lectal_all/api/node_modules/twit/lib/helpers.js:74:13)
    at onRequestComplete (/Users/amills001c/WebstormProjects/lectal_all/api/node_modules/twit/lib/twitter.js:205:25)
    at Request.<anonymous> (/Users/amills001c/WebstormProjects/lectal_all/api/node_modules/twit/lib/twitter.js:225:7)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/amills001c/WebstormProjects/lectal_all/api/node_modules/twit/node_modules/request/request.js:996:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
GET /v1/twitter/followers_list_cursor?data=%7B%22cursorNum%22%3A1%7D 500 488.363 ms - 936
```

any idea if I am doing something wrong?

**Comment by gabrielstuff** [comment]
Apparently you simply are going to far in the twitter cursor for this list of follower

**Comment by ttezel** [comment]
Closing this, reopen if it hasn't been resolved. Thanks!
