### ISSUE TITLE
npm installer gives out an error

### ISSUE THREAD

**Issue by sam95** [ttezel/twit#238]
when I try `npm install twit` or a `sudo npm install twit` I get the following message

    npm http GET https://registry.npmjs.org/twit
	npm ERR! Error: failed to fetch from registry: twit
	npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
	npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
	npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
	npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
	npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
	npm ERR!     at Request.emit (events.js:88:20)
	npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
	npm ERR!     at ClientRequest.emit (events.js:67:17)
	npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
	npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
	npm ERR! You may report this log at:
	npm ERR!     <http://bugs.debian.org/npm>
	npm ERR! or use
    npm ERR!     reportbug --attach /home/pavan/tpass/npm-debug.log npm
    npm ERR! 
    npm ERR! System Linux 3.2.0-48-generic
    npm ERR! command "node" "/usr/bin/npm" "install" "-g" "twit"
    npm ERR! cwd /home/pavan/tpass
    npm ERR! node -v v0.6.12
    npm ERR! npm -v 1.1.4
    npm ERR! message failed to fetch from registry: twit
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/pavan/tpass/npm-debug.log
    npm not ok

**Comment by sam95** [comment]
Solved the issue by running 2 commands, Need to check the versions of node.js and npm before installation
`curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -`
`sudo apt-get install -y nodejs`
