### ISSUE TITLE
FS is not defined

### ISSUE THREAD

**Issue by Exuviax** [ttezel/twit#246]
Error I am getting in my Console (Mac OSX El Capitan)

```
**REMOVED**-MBP:Twitter **REMOVED**$ node bot.js
/Users/**REMOVED**/Documents/Twitter/bot.js:74
var b64content = fs.readFileSync('/path/to/img', { encoding: 'base64' })
                 ^

ReferenceError: fs is not defined
    at Object.<anonymous> (/Users/**REMOVED**/Documents/Twitter/bot.js:74:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

And here is the code I am using

```
var Twit = require('twit');
var fs = Npm.require('fs');
var data = fs.readFileSync(filepathHidden);

var T = new Twit({
  consumer_key:         '**REMOVED**',
  consumer_secret:      '**REMOVED**',
  access_token:         '**REMOVED**',
  access_token_secret:  ' **REMOVED**'
});


function retweetRecent() {
  T.get('search/tweets', {q: "#somehashtag OR #someotherone", result_type: "recent"}, function (err, data,response) {
    if (!err) {
      var retweetId = data.statuses[0].id_str;
      T.post('statuses/retweet/' + retweetId, { }, function (err, response) {
        if (response) {
          console.log('Retweeted Tweet ID: ' + retweetId);
        }
        if (err) {
          console.log('Retweet Error: ', err);
        }
      });
    } else {
      console.log('Search Error: ', err);
    }
  });
}

retweetRecent();
setInterval(retweetRecent, 120000);

```

**Comment by amenadiel** [comment]
Try using require('fs') instead of npm.require('fs')

**Comment by ttezel** [comment]
agreed with @amenadiel

**Comment by onojatreasure** [comment]
`var fs = require('fs');`
works fine
