### ISSUE TITLE
Zlib._handle.onerror unexpected end of file

### ISSUE THREAD

**Issue by Brideau** [ttezel/twit#300]
I am receiving the same error as mentioned in issue https://github.com/ttezel/twit/issues/269, but the solution mentioned there there does not fix the problem for me.

I'm using twit version 2.2.4, with the following configuration:

``` javascript
const keys = {
    consumer_key : process.env.TWITTER_CONSUMER_KEY,
    consumer_secret : process.env.TWITTER_CONSUMER_SECRET,
    access_token : process.env.TWITTER_ACCESS_TOKEN,
    access_token_secret : process.env.TWITTER_ACCESS_TOKEN_SECRET,
    timeout_ms: 60*1000,
  };
```

I've tried it both with and without the trailing comma at the end. It works for an extended period of time (usually a day or two), but then fails abruptly with this error:

```
events.js:160
    throw er; // Unhandled 'error' event
    ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17)
```

The tweet emitter is started and consumed using the following functions (I was testing different geographic areas, hence the geo filter that covers the whole planet):

``` javascript
const client = new Twitter(keys);
const twitEmitter = client.stream('statuses/filter',
  {locations: '-180,-89,180,89'});

twitEmitter.on('tweet', (tweet) => {
  filterForwardLog(tweet);
});

twitEmitter.on('disconnect', (disconnectMessage) => {
  winston.log('warning', 'Connection terminated: ');
  reject(disconnectMessage);
});

twitEmitter.on('connect', () => {
  winston.log('info', 'Connection attempted.');
});

twitEmitter.on('connected', () => {
  winston.log('info', 'Connection successful.');
});

twitEmitter.on('reconnect', (req, res, interval) => {
  winston.log('notice', `Reconnecting in ${interval / 1000.0} seconds`);
});

twitEmitter.on('warning', (warning) => {
  winston.log('warn', warning);
});
```

**Comment by olalonde** [comment]
Same thing here. This bug alone accounts for like 90%+ of my error logs, pretty annoying. 

```javascript
{ Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17) errno: -5, code: 'Z_BUF_ERROR' }
error:  Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17)
```

**Comment by olalonde** [comment]
Created an issue on node (https://github.com/nodejs/node/issues/8701) just in case. I reviewed the twit code and it doesn't seem to do anything out of ordinary with the zlib streams. And if it was just an error that was thrown if a connection closes early or timeout, I suppose googling for that error would bring more results but it doesn't.

**Comment by chasset** [comment]
Hello, I have the same `Z_BUF_ERROR`. I would like to share a clue of the reason and the solution:

> Twitter sends tweets in chunks. Sometimes, some chunks get lost. This throws an error when `zlib` tries to look for an end of the tweet. A correct behaviour for `Twit` would be to stay connected and to wait for the next good tweet.

I discover this developing in Perl my own library to do what `Twit` does.

What do you think about it?

**Comment by hoodsy** [comment]
Anyone have a temporary workaround or fix? This is basically shut down my application.

**Comment by ioRekz** [comment]
Yes same here, quite random since few days

**Comment by hoodsy** [comment]
@ioRekz do you remember changing anything around the time this happened? Could this be a change on Twitter's end with the streaming API?

**Comment by CTassisF** [comment]
This error always existed for me but it was quite intermittent, but today it got worse. Twitter Streaming API is closing too much connections today (maybe due to DNS problems they had with Dyn), you can see that yourself using cURL to stream (the TCP session should disconnect in a few seconds).
The problem with ttezel/twit is that it can't handle connections being abruptly closed by Twitter streaming endpoint. ttezel/twit needs to be able to handle these events and try to reconnect streams incrementally, but I do not know how to do that :/

**Comment by hoodsy** [comment]
@CTassisF my connection is polling, so it will reconnect after a short period of time. Must be related to the DNS attack on Dyn, as you say.

**Comment by CTassisF** [comment]
This issue might be related to NodeJS. I was using NodeJS 6.9.1 from [nodesource/distributions](https://github.com/nodesource/distributions) but I decided to abandon it and try to use the NodeJS 4.6.0 from Debian Stretch official mirror. With NodeJS 4.6.0 the issue is gone.

**Comment by austinhuang0131** [comment]
Same here, started today.

**Comment by olalonde** [comment]
@CTassisF I tried opening an issue https://github.com/nodejs/node/issues/8701 but didn't have time to write some code to reproduce. I'm using Node v6. Maybe https://github.com/ttezel/twit/pull/304 will magically fix the bug? 😜

**Comment by ioRekz** [comment]
Who is using heroku ? I don't seem to have any error when starting the server locally.

**Comment by ioRekz** [comment]
@hoodsy Ho thought I answered but no, I'm sure I didn't change anything

**Comment by ioRekz** [comment]
@CTassisF I don't have the same behavior. It's almost every favorite and track events in my case that raise this error

**Comment by olalonde** [comment]
Not Heroku but Docker

**Comment by KManu** [comment]
Started using twit today, getting the same issue here.

**Comment by vanita5** [comment]
I get the same error since today.

```
Stream error: undefined
{ Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17) errno: -5, code: 'Z_BUF_ERROR' }
```

**Comment by calbertts** [comment]
Using NodeJS 4.6.0 the issue is gone, not sure if it has something to do with it.

**Comment by eduardbosch** [comment]
Like @calbertts & @CTassisF I confirm that issue is gone in NodeJS 4.6.0

**Comment by SeanEire** [comment]
Node 4.6.1 resolves this for me also.

**Comment by ioRekz** [comment]
Same, does anyone has an idea of what's different on 4.6.0 / 4.6.1 ?

**Comment by CTassisF** [comment]
I commented on nodejs/node#8701 saying that there is no issue on 4.6.0/4.6.1, but I don't know how to troubleshoot this any further.

**Comment by chasset** [comment]
Node 4.6.1 resolves the problem too.

**Comment by CTassisF** [comment]
Even running Node 4.6.1 I had some problems today. Again. Did you see the same?

I also found out that Twitter has a community site with real Twitter staff there. They are aware of issues with streaming endpoints. You can see it here: https://twittercommunity.com/t/issues-reported-with-streams-since-10-21/76429

I also noticed that the IPs for all streaming endpoints have changed and after that the issue is gone again. Did not try with Node 6.9.1, but I think they might have fixed it for good. I posted about this in the community: https://twittercommunity.com/t/issues-reported-with-streams-since-10-21/76429/5?u=ctf

**Comment by super-ienien** [comment]
Hi guys. I've got this issue since several months. It became even more frequent since the DDOS attack. What I did to solve the problem was to fork twit and disable gzip for the stream API. Now it works perfectly

**Comment by conradoplg** [comment]
This seems related to the [SO question](https://stackoverflow.com/questions/33926969/how-can-i-avoid-zlib-unexpected-end-of-file-when-gunzipping-partial-files) which mentions [this change](https://github.com/nodejs/node/pull/2595) introduced in node.js 5, though I haven't examined the details

**Comment by chasset** [comment]
@super-ienien How have you done that?

**Comment by super-ienien** [comment]
I did that like this : https://github.com/super-ienien/twit/commit/982d227347256a958f09f6c1062437a5cdb91081

But do not use my fork because it's not up to date with twit last version

**Comment by mhoanghold** [comment]
@super-ienien I used your fork and separately, just your changes, but I am still getting Z_BUF_ERROR and Z_DATA_ERROR

**Comment by ioRekz** [comment]
I didnt change anything for sure. It's running on heroku and I didnt
updated the app for a while

**Comment by chasset** [comment]
How have you done that?

**Comment by SeanEire** [comment]
Has anyone tried using Node v7 to see if this makes any difference? I haven't had a chance to try it out yet.

**Comment by izumskee** [comment]
@SeanEire for me bug is gone with Node v7

**Comment by olalonde** [comment]
Yep, haven't seen this issue in my logs for the past >24h.

**Comment by olalonde** [comment]
Had this happen again today, but it's definitely not often as before.

**Comment by chasset** [comment]
The error from last month is back.

I launch a `statuses/sample` stream and I get tweets during one minute. Then this error is emitted.

```
Error: {
  "errno": -5,
  "code": "Z_BUF_ERROR"
}
```

This stops the reception of tweets. After a minute, twit try to reconnect normally. This cycle repeats itself forever: one minute of tweets and one minute of silence.

* **Version**: node v7.2.0 – Twit 2.2.5
* **Platform**: Linux 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Brideau** [comment]
@chasset Are you still getting this error running 4.6.x? I ended up switching libraries, but the other library has the same problem (only it fails silently...which is worse). If running it on an older version of Node works, that's good enough for me for now.

**Comment by conradoplg** [comment]
I've been running for weeks with my PR #309, no problems so far

**Comment by olalonde** [comment]
@ttezel can we merge this plz? :)

**Comment by chasset** [comment]
@Brideau Yes, with node 4.6.2, I still have this problem

**Comment by chasset** [comment]
@Brideau I try on another machine (macOS Sierra) and it works well with node 6.9

**Comment by chasset** [comment]
@Brideau I try on another machine (macOS Sierra) with node 6.9 but I get the same error periodically (1-3 minutes). 

But, it happens only on heavy streams like:
- statuses/filter with a bounding box of [-180,-90,180,90] or
- statuses/sample.

**Comment by pantchox** [comment]
Hi,
Consider this code snippet
```
var stream = T.stream('statuses/sample')
stream.on('tweet', function (tweet) {
    console.log(tweet);
});
```
Another example to receive this error if i simply unplug my wifi card.

is there something like a try catch that can be implemented to try to bypass this issue?
Thanks.

**Comment by pantchox** [comment]
Sorry on my previous post, if you do
```
stream.on('error', (err) => {
  console.log('error!', err);
});
```
the program is not exiting which is perfect.

**Comment by cstephen** [comment]
What @pantchox says works for me, too. I was also able to replicate the error by cutting off internet access (disabling my virtual machine's network adapter) while my script was running. Here's my understanding of what's going on:

Abruptly cutting off the Twitter stream emits a gunzip "error" event that's handled by the following listener in `streaming-api-connection.js` (at line 138 currently):

```
gunzip.on('error', function (err) {
  self.emit('error', err);
})
```

This code re-emits the "error" event. You need to add a listener to your script to handle it, like @pantchox said:

```
stream.on('error', (err) => {
  console.log('error!', err);
});
```

If you don't handle the "error" event in your script, Node.js will handle it for you by exiting. See https://nodejs.org/api/events.html#events_error_events

"If an EventEmitter does not have at least one listener registered for the 'error' event, and an 'error' event is emitted, the error is thrown, a stack trace is printed, and the Node.js process exits."

**Comment by kud** [comment]
The workaround works here for me too; but is it normal? Is it happening because of network troubles?

**Comment by yrtejas** [comment]
Restarting the app or checking for a previous running instance of the app helped me.
