### ISSUE TITLE
Error: Socket hang up

### ISSUE THREAD

**Issue by jcmidia** [ttezel/twit#341]
Hello! I'm trying to post a media on Twitter, but I'm getting this error when I call the function postMediaChunked

`{ Error: socket hang up                                                                                                    at createHangUpError (_http_client.js:254:15)                                                                          at TLSSocket.socketOnEnd (_http_client.js:346:23)                                                                      at emitNone (events.js:91:20)                                                                                          at TLSSocket.emit (events.js:185:7)                                                                                    at endReadableNT (_stream_readable.js:974:12)                                                                          at _combinedTickCallback (internal/process/next_tick.js:74:11)                                                         at process._tickCallback (internal/process/next_tick.js:98:9) code: null, statusCode: null, allErrors: [], twitterReply: '' }`

My node version is 6.10.0
And I'm running the application on a Windows Server, I don't know if it can be a problem :/ hahaha

**Comment by shalvah** [comment]
Getting this same issue randomly on Node 8.10 on statuses/update. I'm not using a streaming endpoint. Anyone got any ideas?

**Comment by shalvah** [comment]
Turned out I wasn't awaiting the promises correctly. 😅
