### ISSUE TITLE
Bad Twitter streaming request: 401

### ISSUE THREAD

**Issue by Bibab** [ttezel/twit#444]
Would appreciate some help. I think I am using the stream API correctly, but I get this error when I run my app. I have tried two different sets of keys too.

Error: Bad Twitter streaming request: 401
app.js:12
Error: Bad Twitter streaming request: 401
app.js:13
    at Object.exports.makeTwitError (c:\Users\Hasht Ketaab\rct.notifier\node_modules\twit\lib\helpers.js:74:13)
    at Request.<anonymous> (c:\Users\Hasht Ketaab\rct.notifier\node_modules\twit\lib\streaming-api-connection.js:96:29)
    at Request.emit (events.js:132:15)
    at Request.emit (domain.js:421:20)
    at IncomingMessage.<anonymous> (c:\Users\Hasht Ketaab\rct.notifier\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:219:13)
    at IncomingMessage.emit (events.js:132:15)
    at IncomingMessage.emit (domain.js:421:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)

This is how I am setting up the stream:

const Twitter = require('twit');
const config = require('../services-config');

const Credentials = config.twittercredentials;
var T = new Twitter(Credentials);

var filters = config.signalscanSettings.twitterStream.filters;
console.log(filters);

module.exports = {
    startscan: function(){
        var stream = T.stream('statuses/filter', filters);
        stream.on('tweet', function (tweet) {
            console.log(`TWITTER-SIGNAL-STREAM (NEW TWEET): ${tweet}`);
            processtweet(tweet);
          })
......

**Comment by maziyarpanahi** [comment]
The important part for debugging this is in `filters`. Can you show us what is in it? Maybe the output if `console.log(filters);`?

**Comment by Bibab** [comment]
Thanks! Fixed it now. Rookie mistake. Some string manipulation gone wrong.

**Comment by amandeepmittal** [comment]
@maziyarpanahi @Bibab I am getting the same error on issue #452. Can you please help?
