### ISSUE TITLE
I am getting an error on runtime

### ISSUE THREAD

**Issue by amandeepmittal** [ttezel/twit#452]
```shell
events.js:183
2018-07-04T07:02:44.513154+00:00 app[worker.1]:       throw er; // Unhandled 'error' event
2018-07-04T07:02:44.513157+00:00 app[worker.1]:       ^
2018-07-04T07:02:44.513158+00:00 app[worker.1]: 
2018-07-04T07:02:44.513160+00:00 app[worker.1]: Error: Bad Twitter streaming request: 401
2018-07-04T07:02:44.513163+00:00 app[worker.1]:     at Object.exports.makeTwitError (/app/node_modules/twit/lib/helpers.js:74:13)
2018-07-04T07:02:44.513165+00:00 app[worker.1]:     at Request.<anonymous> (/app/node_modules/twit/lib/streaming-api-connection.js:96:29)
2018-07-04T07:02:44.513166+00:00 app[worker.1]:     at emitOne (events.js:121:20)
2018-07-04T07:02:44.513168+00:00 app[worker.1]:     at Request.emit (events.js:211:7)
2018-07-04T07:02:44.513171+00:00 app[worker.1]:     at IncomingMessage.<anonymous> (/app/node_modules/twit/node_modules/request/request.js:1079:12)
2018-07-04T07:02:44.513172+00:00 app[worker.1]:     at Object.onceWrapper (events.js:313:30)
2018-07-04T07:02:44.513174+00:00 app[worker.1]:     at emitNone (events.js:111:20)
2018-07-04T07:02:44.513175+00:00 app[worker.1]:     at IncomingMessage.emit (events.js:208:7)
2018-07-04T07:02:44.513178+00:00 app[worker.1]:     at endReadableNT (_stream_readable.js:1064:12)
2018-07-04T07:02:44.513181+00:00 app[worker.1]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2018-07-04T07:02:44.513182+00:00 app[worker.1]:     at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by maziyarpanahi** [comment]
Hi @amandeepmittal,

It would be really helpful to have look at your code. The stream and what you are tracking.

**Comment by hannahmiller515** [comment]
I, too, am getting this error. I can perform a search just fine, but I get this error when I try to stream:
```
{ Error: Bad Twitter streaming request: 401
    at Object.exports.makeTwitError (/myapp/node_modules/twit/lib/helpers.js:74:13)
    at Request.<anonymous> (/myapp/node_modules/twit/lib/streaming-api-connection.js:96:29)
    at emitOne (events.js:120:20)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/myapp/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  message: 'Bad Twitter streaming request: 401',
  code: null,
  allErrors: [],
  twitterReply: '<html>\\n<head>\\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\\n<title>Error 401 Unauthorized</title>\n</head>\n<body>\n<h2>HTTP ERROR: 401</h2>\n<p>Problem accessing \'/1.1/statuses/sample.json\'. Reason:\n<pre>    Unauthorized</pre>\n</body>\n</html>\n',
  statusCode: 401 }
```

CODE:
```
var twitter_config = {
    consumer_key: '...',
    consumer_secret: '...',
    access_token: '...',
    access_token_secret: '...',
      
    app_only_auth: true
}

// TWITTER STREAM AND HANDLERS
var twit = require('twit');
var Twitter = new twit(twitter_config);

Twitter.get('search/tweets', { q: 'banana', count: 2 }, function(err, data, response) {
  console.log(data);    // Note: Not showing the output from this search above
});


var stream = Twitter.stream('statuses/sample');

stream.on('error', function(err) {
    console.log(err);
});

stream.on('tweet', function (tweet) {
    console.log('tweet');
});
```

**Comment by hannahmiller515** [comment]
I was having this exact same error simply trying to use the 'statuses/sample' endpoint. However, I was also using a Twitter configuration that had app_only_auth set to true. After removing this setting I no longer get the error. Maybe make sure you aren't using app only authentication.

**Comment by amandeepmittal** [comment]
I am closing this issue as the problem I have found was with the tokens.

**Comment by danielriddell21** [comment]
@amandeepmittal Im having a similar issue. What was wrong with your tokens?

**Comment by amandeepmittal** [comment]
Generate new tokens from Twitter app section. It will be solved.
