### ISSUE TITLE
Streaming error: The Site Streams and User Streams endpoints have been turned off. Please migrate to alternate APIs. See https://t.co/usss

### ISSUE THREAD

**Issue by CryptoSharon** [ttezel/twit#477]
My code:

```js
const Twit = require('twit')
const config = require('./config')
const twit = new Twit(config)

const onFollowed = () => console.log('followed')

const stream = twit.stream('user')
stream.on('follow', onFollowed)
stream.on('error', console.error)
```

The error:

```js
{ Error: Bad Twitter streaming request: 410
    at Object.exports.makeTwitError (C:\Users\pc\projects\socialfluff\node_modules\twit\lib\helpers.js:74:13)
    at Request.<anonymous> (C:\Users\pc\projects\socialfluff\node_modules\twit\lib\streaming-api-connection.js:96:29)
    at Request.emit (events.js:187:15)
    at IncomingMessage.<anonymous> (C:\Users\pc\projects\socialfluff\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message: 'Bad Twitter streaming request: 410',
  code: null,
  allErrors: [],
  twitterReply:
   'The Site Streams and User Streams endpoints have been turned off. Please migrate to alternate APIs. See https://t.co/usss\r\n',
  statusCode: 410 }
```

I found an article that explains the changes: https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746

**Comment by maziyarpanahi** [comment]
As it was discussed before, those two API endpoints are deprecated. For the moment there is no support for the new Account Activity and User activity APIs from Twit, please use other libraries.
