### ISSUE TITLE
postMediaChunked Hangs

### ISSUE THREAD

**Issue by ImDestinedMe** [ttezel/twit#481]
Trying to upload a 7MB video using `postMediaChunked` takes over a minute to respond for some reason.
I made sure the video is the right codec by trying to upload it through the website and that responds almost instantly, but this hangs for some reason.

`twit.postMediaChunked({ file_path: file }, function (err, data, resp) {
        if (err) {
            console.log(`Failed: ${err}`)
        }
        else {
            console.log(data)
        }
    })`

**Comment by arjunkomath** [comment]
I'm facing the same issue, uploading GIF images fail and I see this error:
```
{ Error: ETIMEDOUT
at Timeout._onTimeout (/var/task/node_modules/request/request.js:845:19)
at ontimeout (timers.js:482:11)
at tryOnTimeout (timers.js:317:5)
at Timer.listOnTimeout (timers.js:277:5)
code: null,
connect: true,
statusCode: null,
allErrors: [],
twitterReply: '' }
```

**Comment by arjunkomath** [comment]
@ImDestinedMe Try this fix #482
