### ISSUE TITLE
Bad Twitter streaming request: 403

### ISSUE THREAD

**Issue by VoidGekido** [ttezel/twit#574]
i don't really know how to switch to v2 i was hoping someone could help me with it or is there something wrong with the code?
![image_2022-07-05_180616712](https://user-images.githubusercontent.com/86328797/177370441-92e1fa78-d0ee-471f-90a4-0cda4c482e54.png)

Error: Bad Twitter streaming request: 403
    at Object.exports.makeTwitError (F:\AI-CHIBI\node_modules\twit\lib\helpers.js:74:13)
    at Request.<anonymous> (F:\AI-CHIBI\node_modules\twit\lib\streaming-api-connection.js:96:29)
    at Request.emit (node:events:532:35)
    at Gunzip.<anonymous> (F:\AI-CHIBI\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:639:28)
    at Gunzip.emit (node:events:520:28)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on StreamingAPIConnection instance at:
    at Request.<anonymous> (F:\AI-CHIBI\node_modules\twit\lib\streaming-api-connection.js:99:14)
    at Request.emit (node:events:532:35)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: null,
  allErrors: [],
  twitterReply: '<html>\\n<head>\\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\\n<title>Error 403 \n' +
    'Please use V2 filtered and sample volume stream as alternatives\n' +
    '</title>\n' +
    '</head>\n' +
    '<body>\n' +
    '<h2>HTTP ERROR: 403</h2>\n' +
    "<p>Problem accessing '/1.1/statuses/filter.json'. Reason:\n" +
    '<pre>    \n' +
    'Please use V2 filtered and sample volume stream as alternatives\n' +
    '</pre>\n' +
    '</body>\n' +
    '</html>\n',
  statusCode: 403
}

**Comment by mahdikhan786** [comment]
Did you found any solution ?

**Comment by AlexandruMares** [comment]
Is this thing still works?

**Comment by urko-b** [comment]
I think this is happening: https://github.com/ttezel/twit/issues/571#issuecomment-1246081326

**Comment by anthonyattard** [comment]
Getting this error today, shame to see Twitter api being made worse.

**Comment by atnjqt** [comment]
@anthonyattard any resolution? Funny enough, I also ran into this yesterday March 16 2023

**Comment by anthonyattard** [comment]
> @anthonyattard any resolution? Funny enough, I also ran into this yesterday March 16 2023

Looks like the resolution is to hit the v2 endpoints but this library hasn't been updated for it. May have to find an alternative or fork this one. Elon finally cut us off!

**Comment by anthonyattard** [comment]
@atnjqt replace twit with the official twtitter v2 api library https://github.com/twitterdev/twitter-api-typescript-sdk Had to rework my project but am back up and running!
